apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-source-restriction
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'dev'
    server: '*'
  sourceRepos:
  - '*' ## '*' means we are allowed to use any repos
